DROP TABLE IF EXISTS WCR_WELLHEAD;
CREATE TABLE IF NOT EXISTS WCR_WELLHEAD (
    UWI VARCHAR(64) PRIMARY KEY NOT NULL,
    WELL_NAME VARCHAR(255),
    FIELD VARCHAR(255),
    RELEASE_NAME VARCHAR(255),
    LOCATION_TYPE VARCHAR(128),
    BOTTOM_LONG FLOAT,
    BOTTOM_LAT FLOAT,
    SURFACE_LONG FLOAT,
    SURFACE_LAT FLOAT,
    CATEGORY VARCHAR(255),
    WELL_PROFILE VARCHAR(64),
    TARGET_DEPTH FLOAT,
    DRILLED_DEPTH FLOAT,
    LOGGERS_DEPTH FLOAT,
    K_B FLOAT,
    G_L FLOAT,
    RIG VARCHAR(255),
    SPUD_DATE VARCHAR(11),
    HERMETICAL_TEST_DATE VARCHAR(11),
    DRILLING_COMPLETED_DATE VARCHAR(11),
    RIG_RELEASED_DATE VARCHAR(11),
    FORMATION_AT_TD VARCHAR(255),
    RELEASE_ORDER_NO VARCHAR(255),
    OBJECTIVE TEXT,
    STATUS TEXT,
    ID INTEGER,
    MODEL VARCHAR(25),
    INSERT_DATE DATE,
    MATCH_PERCENT FLOAT,
    VECTOR_IDS VARCHAR(100),
    PAGE_NUMBERS VARCHAR(100)
);

DROP TABLE IF EXISTS WCR_CASING;
CREATE TABLE IF NOT EXISTS WCR_CASING (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    UWI VARCHAR(64) NOT NULL,
    CASING_TYPE VARCHAR(255),
    CASING_LINER_NAME VARCHAR(255),
    CASING_START_DATE DATE,
    CASING_TOP FLOAT,
    CASING_BOTTOM FLOAT,
    OUTER_DIAMETER FLOAT,
    CASING_SHOE_LENGTH FLOAT,
    FLOAT_COLLAR FLOAT,
    MATERIAL_TYPE VARCHAR(64),
    WEIGHT VARCHAR(64),
    STEEL_GRADE VARCHAR(64),
    REMARKS TEXT,
    MODEL VARCHAR(25),
    INSERT_DATE DATE,
    MATCH_PERCENT FLOAT,
    VECTOR_IDS VARCHAR(100),
    PAGE_NUMBERS VARCHAR(100),
    MATCH_ID INTEGER
);

DROP TABLE IF EXISTS WCR_LOGSRECORD;
CREATE TABLE IF NOT EXISTS WCR_LOGSRECORD (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    UWI VARCHAR(64) NOT NULL,
    TOP FLOAT,
    BOTTOM FLOAT,
    LOG_RECORDED VARCHAR(255),
    LOG_DATE VARCHAR(11),
    LOGGED_BY VARCHAR(64),
    MODEL VARCHAR(25),
    INSERT_DATE DATE,
    MATCH_PERCENT FLOAT,
    VECTOR_IDS VARCHAR(100),
    PAGE_NUMBERS VARCHAR(100),
    MATCH_ID INTEGER
);

DROP TABLE IF EXISTS WCR_DIRSRVY;
CREATE TABLE IF NOT EXISTS WCR_DIRSRVY (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    UWI VARCHAR(64),
    MD FLOAT,
    ANGLE_INCLINATION FLOAT,
    AZIMUTH FLOAT,
    NS FLOAT,
    EW FLOAT,
    NET_DRIFT FLOAT,
    NET_DIRECTION_ANGLE FLOAT,
    VERTICAL_SHORTENING FLOAT,
    MODEL VARCHAR(25),
    INSERT_DATE DATE,
    MATCH_PERCENT FLOAT,
    VECTOR_IDS VARCHAR(100),
    PAGE_NUMBERS VARCHAR(100),
    MATCH_ID VARCHAR(100)
);

DROP TABLE IF EXISTS WCR_SWC;
CREATE TABLE IF NOT EXISTS WCR_SWC (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    UWI VARCHAR(64),
    DEPTH FLOAT,
    RECOVERED_LENGTH FLOAT,
    LITHOLOGY VARCHAR(255),
    LITHOLOGY_DESCRIPTION TEXT,
    HCSHOW VARCHAR(255),
    REMARKS VARCHAR(255),
    MODEL VARCHAR(25),
    INSERT_DATE DATE,
    MATCH_PERCENT FLOAT,
    VECTOR_IDS VARCHAR(100),
    PAGE_NUMBERS VARCHAR(100),
    MATCH_ID INTEGER
);

DROP TABLE IF EXISTS WCR_HCSHOWS;
CREATE TABLE IF NOT EXISTS WCR_HCSHOWS (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    UWI VARCHAR(64),
    TOP_DEPTH FLOAT,
    BOTTOM_DEPTH FLOAT,
    TOTAL_GAS VARCHAR(255),
    LITHOLOGY VARCHAR(255),
    HCSHOW VARCHAR(255),
    MODEL VARCHAR(25),
    INSERT_DATE DATE,
    MATCH_PERCENT FLOAT,
    VECTOR_IDS VARCHAR(100),
    PAGE_NUMBERS VARCHAR(100),
    MATCH_ID INTEGER
);
